[workspace]
members = [".", "executor", "lock"]

[package]
name = "colorless"
version = "0.1.0"
edition = "2024"

[dependencies]
corosensei = "0.2.1"
pin-project-lite = "0.2.16"

[features]
tlv = []

[dev-dependencies]
futures-lite = "2.6.0"
